### ISSUE TITLE
[SVGLab1] Drawing line jumps to a fixed point at certain interval creates iincorrect result while using touch input

### ISSUE THREAD

**Issue by quarkli** [quarkli/gatherhub#10]
Description:
This issue is found on some mobile phone browser. Where user drawing with touch screen, the drawing path keeps jumping back to a fixed point at a fixed interval which created a weird triangular shape.

**Comment by quarkli** [comment]
Reason:
After investigation, this issue 'should be' caused by the incorrect touch event handling in some browsers. 

The problematic code was in mousemoveHandler() which should not even be triggered by touch event. Moreover, the problematic code was setCursorImage() which is to set 'mouse' cursor to respective shape according to the action and it is, again, totally irrelevant to touch event. However, once we remove this line, all problems are gone.

** While reviewing the code, we also found it is an unnecessary and redundant code and are going to remove it. The mouse cursor should be changed at mouse down or up event. There is no need to update mouse cursor during moving.

Conclusion:
According to the investigation and tests, we 'believe' the problem is some browsers did not well implement the touch event and translated it to mouse event which causes such strange issue.

**Comment by quarkli** [comment]
fixed in 11f2becf0a03afb7f7e2d508f8de09cbfd38a03d

**Comment by Phenix2014** [comment]
I see...
