### ISSUE TITLE
Adding user typing/drawing detection and notification function

### ISSUE THREAD

**Issue by quarkli** [quarkli/gatherhub#16]
Description:
When user is typing a message or drawing, we can send a 'user typing/drawing' event to the server to notify other peers. The notification is better to be a blinking icon in the peer list.

**Comment by rycstar** [comment]
The notification is better to be a string like "<username> is typing ..."

**Comment by quarkli** [comment]
51c853c77d9aa914ae14e8978aec4c164bc2f1e4
When a user starts drawing, a prompt of peer name will be displayed in the relative position of sketchpad on all remote peers.

**Comment by Phenix2014** [comment]
wonderful.

**Comment by quarkli** [comment]
9a70e147594ccd97f513dba89ef50a2239781d0b
Primitive implementation done
