### ISSUE TITLE
design and wrap webRtc class 

### ISSUE THREAD

**Issue by Phenix2014** [quarkli/gatherhub#17]
## Description:
We have just built a communication engine  demo to make browsers to send text message to each others and let one browsers do audio broadcasting to others. Now we need a wrap class with api export to be used by gatherhub.

## class webRtc

Public:
* constructor (hubName, userName, config)
* send(to,type, content)
* onReceive(from,type,content)
* startAudioCasting()
* stopAudioCasting()
* getAtrribute(attrName)
* setAtrribute(attrName:value)
* getUserList() {return name[];}
* setMsgHistory()

**Comment by quarkli** [comment]
I have some advice. It's ok to start with some primitive design specifications, but don't take it too seriously. It is highly likely to have lots changes during the development. Just don't limit yourself to a solid idea. Simply starting with something basic and adding things up as needed.

**Comment by Phenix2014** [comment]
rework the webRtc engine. It has not full features finished yet.
https://github.com/quarkli/gatherhub/commit/665e55f080867c21d438a5f2eb12bff03e836b02
only fulfilled 
1, rearranged source code structure.
2,finished building peers on mesh network with data exchanging channel.
3,finished   audio/video lib source code.
4,finished screen casting lib source code.
5, use hubcom.js to manage the lib code and use main.js to demo the webrtc engine.

Files descriptions:
localmedia.js  file to manipulate local stream media, such as audio/video and screen.
peerconn.js file to use webrtc basic apis to fulfill single peer feature.
webrtc.js file to implement webrtc communication on a group of peers on mesh network.
hubcom.js file for rtc communication engine, it inherit from webrtc and add other features such as audio casting que, extra peers for these clients that does not support webrtc.
sockconn.js file to use socke.io to maintain the signal channel with server.

**Comment by Phenix2014** [comment]
f0a6a9f8e2d0cfcc5e4d279bc0757784a72a09f2
is a complete demo for webrtc.

ps: it only support chrome.
