### ISSUE TITLE
Execution error: illegal access to 'undefined'

### ISSUE THREAD

**Issue by quarkli** [quarkli/gatherhub#19]
File: gatherhub.teleboard.js
Error at: Line 288 289 291
	288		var x = e.pageX || e.touches[0].pageX;
	289		var y = e.pageY || e.touches[0].pageY;
	291		if (e.pageX || e.touches.length == 1) {

Function: VisualPad() { this.canvas.on('mousemove touchmove', function(){}}

Description:
The issue occurs only when dragging VisualPad object to the top or left edge of the window with mouse. It is because when mouse move to the top or left edge of the window, the value of e.pageY or e.pageX is 0 which equals to 'false'. Hence, the interpreter continue to process e.touchex[0].pageX (pageY or length) - this causes error because touch event was not presented.

**Comment by quarkli** [comment]
The first straightforward solution is to change the code by evaluating whether a mouse event is 'undefined' then get the value from valid event source. However, this approach added additional lines which looks inefficient and ugly. Here is the proposed solution:

			var x = Math.round(e.pageX + 0.1 || e.touches[0].pageX);
			var y = Math.round(e.pageY + 0.1 || e.touches[0].pageY);
			if (e.pageX + 0.1 || e.touches.length == 1) {

Instead of adding evaluation method, I just tweak the original code a little bit. By adding a small value to e.pageX or e.pageY, it prevent it from resulting 0 as false value and rounded it back to 0 after evaluation. As for the if statement, there is no need to rounded the value. This solution is to leverage the 'undefined + n = undefined' characteristic.

P.S.
The order of the evaluation DOES matter a lot. When it is triggered by touch event, e.pageX and e.pageY is 'undefined' and vice versa, when it is triggered by mouse event, e.touches is 'undefined'. It is ok to evaluation 'undefined' object or event do mathematical operation on it, but it is not allow to read any property from it because it has none. Therefore, when event is triggered by touch, e.pageX is 'undefined' which equal to false then code process get to e.touches, but if we reverse the order and the event is triggered by mouse, e.touches will be 'undefined' and we try to read e.touches.something will cause execution error.

**Comment by Phenix2014** [comment]
a very smart solution....
greate.

2015-10-22 20:10 GMT+08:00 Quark Li <notifications@github.com>:

**Comment by quarkli** [comment]
I thought so too, but unfortunately, when I tested it on the mobile phone with webkit browser, I found the 'undefined'+1='undifine' trick does not work. Therefore, I have to change the code again to make sure it works on different browser. It is a cruel fact that not all browser follows the standard and we cannot get rid of issues like these.

**Comment by Phenix2014** [comment]
that's alright, you always got great ideas.
