### ISSUE TITLE
New Teleboard object might consume lots memory

### ISSUE THREAD

**Issue by quarkli** [quarkli/gatherhub#21]
Description:
It is noticed in Chrome Task Manager that the memory consumption of the new Teleboard implementation can sometimes jump to 160MB up. I need to run a deep investigation to find the high memory consumption code and optimize the design.

**Comment by Phenix2014** [comment]
wa ....

**Comment by quarkli** [comment]
It can be reproduced by repeating resizing the window. However, I was doing it in debugging mode, not sure if it has anything to do with the Chrome debugger.

I will leave it a while and check if the memory consumption drops and the I will do resizing without Chrome debugger to make sure it is not related to the Chrome debugger.

**Comment by quarkli** [comment]
The memory consumption dropped after a while and if I resized the window without Chrome debugger, the memory consumption seems not getting increased dramatically. I guess it could be consumed by Chrome debugger, but I will keep monitoring this for while to confirm.

**Comment by Phenix2014** [comment]
In chrome dev tools, there is a Profiles tools. select 'Record Heap Allocations'. It could record heap allocations, by which you could find which element would consume the most memory.

**Comment by quarkli** [comment]
The average inactive memory consumption is around less than 19MB which is quite similar to Google SVG Editor (~20MB). However, the dynamic active memory consumption is around 45~50MB depending on the actions been taken. This may not be too critical for modern PC and Mobiles, but we can certainly review the code thoroughly and optimize it.

Code optimization is a labor effort and time consuming. I will not do it now, but keep performance issue in mind and keep monitoring it during the development, unless there is critical memory leakage found. (Browsers like Chrome has its own protection for application dead loop or lock and will terminate the page automatically, but it may stall the browser or the system for a while until the browser kill the application)

p.s. I took concern on this because I feel my laptop is running out of memory because my desktop icom images were gone and computer is getting slower. I made a reboot and check this issue. This maybe related to Chrome debugger (need to confirm). If so, I should be more careful of running code in debugging mode and maybe close Chrome every once a while and reopen it.

**Comment by quarkli** [comment]
https://github.com/quarkli/gatherhub/issues/21#issuecomment-151701753
I have already run profiling with Chrome dev tool and its mobile emulators (iphone, ipad, Nexus, Galaxy, etc) to run quick mobile compatibility test (but I assume it is simulating 'Chrome' on mobile, not the other browsers, so it might not be too useful and so far, it seems Chrome can best support all HTML5 standard.)

**Comment by quarkli** [comment]
It seems to be ok after running a while later. This might just be a false alarm, close this issue now.
