### ISSUE TITLE
Some questions about node.js workspace and package manager.

### ISSUE THREAD

**Issue by Phenix2014** [quarkli/gatherhub#22]
我一直好奇github的一些工程，原本是前端的javascript代码，但是为啥代码源文件的开头声明引用关系的时候用
var peers =require('test-web-rtc');
而且还不带本地路径名，在工程目录下还找不到这个依存的文件，
源文件结尾用module.exports = Peer;
而且代码也没有考虑前端浏览器异步加载，文件之间的依存关系什么的。
这是什么工作原理呢？

**Comment by Phenix2014** [comment]
昨天顺手看了一下（主要是我用的getScreenMedia就是一个github上的库，依存关系不复杂，我就简单的改成不依赖别的库的源文件放到我工程里。昨天重构代码的时候，就在琢磨，为啥别人的工程里没有把getscreenmedia的代码放进来呢）

研究以后发现，原来这种做法是npm管理前端工程一种模式，npm在工程根目录下有一个package.json，可以在这里添加依赖的库文件，这点有点像rails的工程管理，每个库文件的版本兼容性也一并描述。工程clone到本地以后，在package.json目录下执行npm install，相关的库就会自动打包下来。库里包含前端代码的支持库，就是require的那些库，也包含了开发调试用的库。在工程目录下，还有一个build.js的文件。
打开以后，发现里面的功能是，
var bundle = require('browserify')(), //打包工具
    fs = require('fs'),
    request = require('request'),
    uglify = require('uglify-js');

bundle.add('./your_main');//加载your_main.js
bundle.bundle({standalone: 'YourLibName'}, function (err, source) { // 根据库的依存关系打包成单一文件，并export出全局的库叫YourLibName
    if (err) console.error(err);
    fs.writeFileSync('simplewebrtc.bundle.js', source);
    fs.writeFile('latest.js', uglify.minify(source, {fromString: true}).code, function (err) {//用uglify压缩
        if (err) throw err;
    });
});


用browserify把工程主文件打包成主文件.bundle.js，利用browserify的功能把前端的支持库从刚刚install的node modules里取出来，并一并打包在bundle文件里。打包的方法，是根据commonjs的规则，按依赖的顺序把所有源文件依次打包进来，也同时解决了异步加载的问题。然后再执行uglify-js，对代码进行压缩。如果是上线，就可以用压缩好的js文件。

至于文件开头用 var xxx =require('yyy');结尾用 module.export = zzz;这个是传统的服务器后端开发的代码描述方法。通过browserify可以自动转换成前端的代码。

**Comment by quarkli** [comment]
cool!
2015年11月13日 上午10:58，"Phenix" <notifications@github.com>写道：
