### ISSUE TITLE
When a remote user disconnected, the user's drawing could not be removed

### ISSUE THREAD

**Issue by quarkli** [quarkli/gatherhub#23]
Description:
In new Teleboard, each user can undo/redo his/her own drawing only. Thus, when a user disconnected, if there are any drawings left by the user, no other participants can remove it.

NOTE: we might not want to remove a user's drawing after he/she left, so we need to evaluate which is the best way to handle user leaving case.

**Comment by quarkli** [comment]
Changed undo_all button to clear_all, now any one can clear the canvas.

**Comment by Phenix2014** [comment]
Is there any information promt when clear all is called?

**Comment by quarkli** [comment]
good idea!
2015年11月29日 下午3:06，"Phenix" <notifications@github.com>写道：
