### ISSUE TITLE
Some code seems to be redundant to me

### ISSUE THREAD

**Issue by quarkli** [quarkli/gatherhub#33]
HI, i have some questions about the committed code. Some of them seem to be redundant to me, but maybe there is a reason and you can explain to me. For example,

console.log.apply(console, arguments);
isn't the same as,
console.log(arguments);

and,
    function objSetTimeout(obj,func,time){
        var t;
        t = setTimeout(function(){
            func.call(obj);
        },time);
        return t;
    }
isn't the same as calling setTimeout() directly?

If we wrap some function into a new one but doing nothing different, it seems a redundant to me. If there is something i dont understand or missed, please kindly point out for me. 

if it was just a simple mistake, then dont worry too much, i sometimes made similar mistakes too. However, I usually have the habit to review my own code and looking for inefficiency, redundant and complex logic. I just point this out as a reminder that it might be a good practice for self code review.

**Comment by Phenix2014** [comment]
:-)

about the second function objSetTimeout,
look the below code:

    _proto._reqTimerHdl = function(){
        _infLog(this.id + ' _reqTimerHdl', this.reqCnt);
        this.reqCnt --;
        if(this.reqCnt > 0){
            this._sendCastReq();
            this.reqTimer = objSetTimeout(this,this._reqTimerHdl, t2);
        } ....

The timer interrupt would call himself when timeout happened. If the setTimeout() was used, the 'this' would be equal to 'window', not the internal obj. If we use 'self = this', like setTimeout(self._timerHandler), the self could not be send to timeout handlers.

I had do some experiments for the timer handler, and finally found If I wrapped the timer by keep its 'this' point, the 'this' could be pass to the interrupt handler.

**Comment by Phenix2014** [comment]
about question 1:

    function _infLog(){
        if(_dbgFlag){
            console.log.apply(console, arguments);
        }
    }

First ,I am too lazy, I need wrapped a utils.js to be included.
Second, below two functions are different:

    function _infLog(){
        console.log.apply(console,arguments);
    }

    function _infLog(){
        console.log(arguments);
    }

The first one is a normal function, the second one is a constructor.
If there is no parameter in function declare, the key word 'arguments' would be a special parameters which implied all the parameters array from the function caller. But it must use 'apply' to pass.

**Comment by Phenix2014** [comment]
If we do not use 'apply' obj, we have to write like below:

    function _infLog(title,obj){
        console.log(title,obj);
    }

**Comment by quarkli** [comment]
I see, I kinda get your idea. I see the reason you are doing this is because of 'this'. 
I think it is alright with your explanation, but this implementation still looks indirect and not straightforward to me. I will probably do it differently.

**Comment by quarkli** [comment]
in reply to comment 5,
I think you can totally do this,

function _inflog() {
    console.log(arguments);
}

which i just tested in the browser console.

**Comment by quarkli** [comment]
Sorry, i missed your comment 9, I see the reason.
